# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Charger
PRODUCT_COPY_FILES += \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/battery_01.png:system/etc/charger/1080x1920/battery_01.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/battery_02.png:system/etc/charger/1080x1920/battery_02.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/battery_03.png:system/etc/charger/1080x1920/battery_03.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/battery_04.png:system/etc/charger/1080x1920/battery_04.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/battery_05.png:system/etc/charger/1080x1920/battery_05.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/battery_06.png:system/etc/charger/1080x1920/battery_06.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/battery_07.png:system/etc/charger/1080x1920/battery_07.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/battery_08.png:system/etc/charger/1080x1920/battery_08.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/battery_09.png:system/etc/charger/1080x1920/battery_09.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/bg.png:system/etc/charger/1080x1920/bg.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_00.png:system/etc/charger/1080x1920/charging_00.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_01.png:system/etc/charger/1080x1920/charging_01.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_02.png:system/etc/charger/1080x1920/charging_02.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_03.png:system/etc/charger/1080x1920/charging_03.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_04.png:system/etc/charger/1080x1920/charging_04.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_05.png:system/etc/charger/1080x1920/charging_05.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_06.png:system/etc/charger/1080x1920/charging_06.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_07.png:system/etc/charger/1080x1920/charging_07.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_08.png:system/etc/charger/1080x1920/charging_08.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_09.png:system/etc/charger/1080x1920/charging_09.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_10.png:system/etc/charger/1080x1920/charging_10.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_11.png:system/etc/charger/1080x1920/charging_11.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_12.png:system/etc/charger/1080x1920/charging_12.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_13.png:system/etc/charger/1080x1920/charging_13.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_14.png:system/etc/charger/1080x1920/charging_14.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_15.png:system/etc/charger/1080x1920/charging_15.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_16.png:system/etc/charger/1080x1920/charging_16.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_17.png:system/etc/charger/1080x1920/charging_17.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_18.png:system/etc/charger/1080x1920/charging_18.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_19.png:system/etc/charger/1080x1920/charging_19.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_20.png:system/etc/charger/1080x1920/charging_20.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_21.png:system/etc/charger/1080x1920/charging_21.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_22.png:system/etc/charger/1080x1920/charging_22.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/charging_23.png:system/etc/charger/1080x1920/charging_23.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_00.png:system/etc/charger/1080x1920/clric_00.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_01.png:system/etc/charger/1080x1920/clric_01.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_02.png:system/etc/charger/1080x1920/clric_02.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_03.png:system/etc/charger/1080x1920/clric_03.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_04.png:system/etc/charger/1080x1920/clric_04.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_05.png:system/etc/charger/1080x1920/clric_05.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_06.png:system/etc/charger/1080x1920/clric_06.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_07.png:system/etc/charger/1080x1920/clric_07.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_08.png:system/etc/charger/1080x1920/clric_08.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_09.png:system/etc/charger/1080x1920/clric_09.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_10.png:system/etc/charger/1080x1920/clric_10.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_11.png:system/etc/charger/1080x1920/clric_11.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_12.png:system/etc/charger/1080x1920/clric_12.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_13.png:system/etc/charger/1080x1920/clric_13.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_14.png:system/etc/charger/1080x1920/clric_14.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_15.png:system/etc/charger/1080x1920/clric_15.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_16.png:system/etc/charger/1080x1920/clric_16.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_17.png:system/etc/charger/1080x1920/clric_17.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_18.png:system/etc/charger/1080x1920/clric_18.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_19.png:system/etc/charger/1080x1920/clric_19.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_20.png:system/etc/charger/1080x1920/clric_20.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_21.png:system/etc/charger/1080x1920/clric_21.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_22.png:system/etc/charger/1080x1920/clric_22.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_23.png:system/etc/charger/1080x1920/clric_23.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_24.png:system/etc/charger/1080x1920/clric_24.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_25.png:system/etc/charger/1080x1920/clric_25.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_26.png:system/etc/charger/1080x1920/clric_26.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_27.png:system/etc/charger/1080x1920/clric_27.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_28.png:system/etc/charger/1080x1920/clric_28.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_29.png:system/etc/charger/1080x1920/clric_29.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_30.png:system/etc/charger/1080x1920/clric_30.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_31.png:system/etc/charger/1080x1920/clric_31.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_32.png:system/etc/charger/1080x1920/clric_32.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_33.png:system/etc/charger/1080x1920/clric_33.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_34.png:system/etc/charger/1080x1920/clric_34.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_35.png:system/etc/charger/1080x1920/clric_35.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_36.png:system/etc/charger/1080x1920/clric_36.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_37.png:system/etc/charger/1080x1920/clric_37.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_38.png:system/etc/charger/1080x1920/clric_38.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_39.png:system/etc/charger/1080x1920/clric_39.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_40.png:system/etc/charger/1080x1920/clric_40.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_41.png:system/etc/charger/1080x1920/clric_41.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_42.png:system/etc/charger/1080x1920/clric_42.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_43.png:system/etc/charger/1080x1920/clric_43.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_44.png:system/etc/charger/1080x1920/clric_44.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_45.png:system/etc/charger/1080x1920/clric_45.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_46.png:system/etc/charger/1080x1920/clric_46.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_47.png:system/etc/charger/1080x1920/clric_47.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_48.png:system/etc/charger/1080x1920/clric_48.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_49.png:system/etc/charger/1080x1920/clric_49.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_50.png:system/etc/charger/1080x1920/clric_50.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_51.png:system/etc/charger/1080x1920/clric_51.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_52.png:system/etc/charger/1080x1920/clric_52.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_53.png:system/etc/charger/1080x1920/clric_53.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_54.png:system/etc/charger/1080x1920/clric_54.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_55.png:system/etc/charger/1080x1920/clric_55.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_56.png:system/etc/charger/1080x1920/clric_56.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_57.png:system/etc/charger/1080x1920/clric_57.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_58.png:system/etc/charger/1080x1920/clric_58.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_59.png:system/etc/charger/1080x1920/clric_59.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_60.png:system/etc/charger/1080x1920/clric_60.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_61.png:system/etc/charger/1080x1920/clric_61.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_62.png:system/etc/charger/1080x1920/clric_62.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_63.png:system/etc/charger/1080x1920/clric_63.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_64.png:system/etc/charger/1080x1920/clric_64.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_65.png:system/etc/charger/1080x1920/clric_65.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_66.png:system/etc/charger/1080x1920/clric_66.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_67.png:system/etc/charger/1080x1920/clric_67.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_68.png:system/etc/charger/1080x1920/clric_68.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_69.png:system/etc/charger/1080x1920/clric_69.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_70.png:system/etc/charger/1080x1920/clric_70.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_71.png:system/etc/charger/1080x1920/clric_71.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_72.png:system/etc/charger/1080x1920/clric_72.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_73.png:system/etc/charger/1080x1920/clric_73.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_74.png:system/etc/charger/1080x1920/clric_74.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_75.png:system/etc/charger/1080x1920/clric_75.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_76.png:system/etc/charger/1080x1920/clric_76.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_77.png:system/etc/charger/1080x1920/clric_77.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_78.png:system/etc/charger/1080x1920/clric_78.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_79.png:system/etc/charger/1080x1920/clric_79.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_80.png:system/etc/charger/1080x1920/clric_80.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_81.png:system/etc/charger/1080x1920/clric_81.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_82.png:system/etc/charger/1080x1920/clric_82.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_83.png:system/etc/charger/1080x1920/clric_83.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_84.png:system/etc/charger/1080x1920/clric_84.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_85.png:system/etc/charger/1080x1920/clric_85.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_86.png:system/etc/charger/1080x1920/clric_86.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_87.png:system/etc/charger/1080x1920/clric_87.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_88.png:system/etc/charger/1080x1920/clric_88.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_89.png:system/etc/charger/1080x1920/clric_89.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_90.png:system/etc/charger/1080x1920/clric_90.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_91.png:system/etc/charger/1080x1920/clric_91.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_92.png:system/etc/charger/1080x1920/clric_92.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_93.png:system/etc/charger/1080x1920/clric_93.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_94.png:system/etc/charger/1080x1920/clric_94.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_95.png:system/etc/charger/1080x1920/clric_95.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_96.png:system/etc/charger/1080x1920/clric_96.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_97.png:system/etc/charger/1080x1920/clric_97.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_98.png:system/etc/charger/1080x1920/clric_98.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/clric_99.png:system/etc/charger/1080x1920/clric_99.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/cur_surface.png:system/etc/charger/1080x1920/cur_surface.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_00.png:system/etc/charger/1080x1920/dcp_charging_00.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_01.png:system/etc/charger/1080x1920/dcp_charging_01.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_02.png:system/etc/charger/1080x1920/dcp_charging_02.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_03.png:system/etc/charger/1080x1920/dcp_charging_03.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_04.png:system/etc/charger/1080x1920/dcp_charging_04.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_05.png:system/etc/charger/1080x1920/dcp_charging_05.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_06.png:system/etc/charger/1080x1920/dcp_charging_06.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_07.png:system/etc/charger/1080x1920/dcp_charging_07.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_08.png:system/etc/charger/1080x1920/dcp_charging_08.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_09.png:system/etc/charger/1080x1920/dcp_charging_09.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_10.png:system/etc/charger/1080x1920/dcp_charging_10.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_11.png:system/etc/charger/1080x1920/dcp_charging_11.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_12.png:system/etc/charger/1080x1920/dcp_charging_12.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_13.png:system/etc/charger/1080x1920/dcp_charging_13.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_14.png:system/etc/charger/1080x1920/dcp_charging_14.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_15.png:system/etc/charger/1080x1920/dcp_charging_15.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_16.png:system/etc/charger/1080x1920/dcp_charging_16.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_17.png:system/etc/charger/1080x1920/dcp_charging_17.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_18.png:system/etc/charger/1080x1920/dcp_charging_18.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_19.png:system/etc/charger/1080x1920/dcp_charging_19.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_20.png:system/etc/charger/1080x1920/dcp_charging_20.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_21.png:system/etc/charger/1080x1920/dcp_charging_21.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_22.png:system/etc/charger/1080x1920/dcp_charging_22.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_charging_23.png:system/etc/charger/1080x1920/dcp_charging_23.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/dcp_empty_charge.png:system/etc/charger/1080x1920/dcp_empty_charge.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/empty_charge.png:system/etc/charger/1080x1920/empty_charge.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/err_charge.png:system/etc/charger/1080x1920/err_charge.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_00.png:system/etc/charger/1080x1920/fcp_charging_00.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_01.png:system/etc/charger/1080x1920/fcp_charging_01.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_02.png:system/etc/charger/1080x1920/fcp_charging_02.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_03.png:system/etc/charger/1080x1920/fcp_charging_03.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_04.png:system/etc/charger/1080x1920/fcp_charging_04.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_05.png:system/etc/charger/1080x1920/fcp_charging_05.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_06.png:system/etc/charger/1080x1920/fcp_charging_06.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_07.png:system/etc/charger/1080x1920/fcp_charging_07.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_08.png:system/etc/charger/1080x1920/fcp_charging_08.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_09.png:system/etc/charger/1080x1920/fcp_charging_09.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_10.png:system/etc/charger/1080x1920/fcp_charging_10.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_11.png:system/etc/charger/1080x1920/fcp_charging_11.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_12.png:system/etc/charger/1080x1920/fcp_charging_12.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_13.png:system/etc/charger/1080x1920/fcp_charging_13.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_14.png:system/etc/charger/1080x1920/fcp_charging_14.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_15.png:system/etc/charger/1080x1920/fcp_charging_15.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_16.png:system/etc/charger/1080x1920/fcp_charging_16.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_17.png:system/etc/charger/1080x1920/fcp_charging_17.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_18.png:system/etc/charger/1080x1920/fcp_charging_18.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_19.png:system/etc/charger/1080x1920/fcp_charging_19.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_20.png:system/etc/charger/1080x1920/fcp_charging_20.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_21.png:system/etc/charger/1080x1920/fcp_charging_21.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_22.png:system/etc/charger/1080x1920/fcp_charging_22.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_charging_23.png:system/etc/charger/1080x1920/fcp_charging_23.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/fcp_empty_charge.png:system/etc/charger/1080x1920/fcp_empty_charge.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/full_charge.png:system/etc/charger/1080x1920/full_charge.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_0.png:system/etc/charger/1080x1920/number_0.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_1.png:system/etc/charger/1080x1920/number_1.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_2.png:system/etc/charger/1080x1920/number_2.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_3.png:system/etc/charger/1080x1920/number_3.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_4.png:system/etc/charger/1080x1920/number_4.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_5.png:system/etc/charger/1080x1920/number_5.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_6.png:system/etc/charger/1080x1920/number_6.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_7.png:system/etc/charger/1080x1920/number_7.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_8.png:system/etc/charger/1080x1920/number_8.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/number_9.png:system/etc/charger/1080x1920/number_9.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/percent_sign.png:system/etc/charger/1080x1920/percent_sign.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_00.png:system/etc/charger/1080x1920/scp_charging_00.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_01.png:system/etc/charger/1080x1920/scp_charging_01.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_02.png:system/etc/charger/1080x1920/scp_charging_02.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_03.png:system/etc/charger/1080x1920/scp_charging_03.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_04.png:system/etc/charger/1080x1920/scp_charging_04.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_05.png:system/etc/charger/1080x1920/scp_charging_05.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_06.png:system/etc/charger/1080x1920/scp_charging_06.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_07.png:system/etc/charger/1080x1920/scp_charging_07.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_08.png:system/etc/charger/1080x1920/scp_charging_08.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_09.png:system/etc/charger/1080x1920/scp_charging_09.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_10.png:system/etc/charger/1080x1920/scp_charging_10.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_11.png:system/etc/charger/1080x1920/scp_charging_11.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_12.png:system/etc/charger/1080x1920/scp_charging_12.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_13.png:system/etc/charger/1080x1920/scp_charging_13.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_14.png:system/etc/charger/1080x1920/scp_charging_14.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_15.png:system/etc/charger/1080x1920/scp_charging_15.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_16.png:system/etc/charger/1080x1920/scp_charging_16.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_17.png:system/etc/charger/1080x1920/scp_charging_17.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_18.png:system/etc/charger/1080x1920/scp_charging_18.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_19.png:system/etc/charger/1080x1920/scp_charging_19.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_20.png:system/etc/charger/1080x1920/scp_charging_20.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_21.png:system/etc/charger/1080x1920/scp_charging_21.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_22.png:system/etc/charger/1080x1920/scp_charging_22.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_charging_23.png:system/etc/charger/1080x1920/scp_charging_23.png \
    vendor/honor/stf/proprietary/etc/charger/1080x1920/scp_empty_charge.png:system/etc/charger/1080x1920/scp_empty_charge.png

# Vndk
PRODUCT_COPY_FILES += \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.frameworks.schedulerservice@1.0.so:system/lib/vndk-compat/android.frameworks.schedulerservice@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.frameworks.sensorservice@1.0.so:system/lib/vndk-compat/android.frameworks.sensorservice@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.frameworks.vr.composer@1.0.so:system/lib/vndk-compat/android.frameworks.vr.composer@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.audio.common@2.0-util.so:system/lib/vndk-compat/android.hardware.audio.common@2.0-util.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.audio.common@2.0.so:system/lib/vndk-compat/android.hardware.audio.common@2.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.audio.effect@2.0.so:system/lib/vndk-compat/android.hardware.audio.effect@2.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.audio@2.0.so:system/lib/vndk-compat/android.hardware.audio@2.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.biometrics.fingerprint@2.1.so:system/lib/vndk-compat/android.hardware.biometrics.fingerprint@2.1.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.bluetooth@1.0.so:system/lib/vndk-compat/android.hardware.bluetooth@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.boot@1.0.so:system/lib/vndk-compat/android.hardware.boot@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.broadcastradio@1.0.so:system/lib/vndk-compat/android.hardware.broadcastradio@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.broadcastradio@1.1.so:system/lib/vndk-compat/android.hardware.broadcastradio@1.1.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.camera.common@1.0.so:system/lib/vndk-compat/android.hardware.camera.common@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.camera.device@1.0.so:system/lib/vndk-compat/android.hardware.camera.device@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.camera.device@3.2.so:system/lib/vndk-compat/android.hardware.camera.device@3.2.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.camera.metadata@3.2.so:system/lib/vndk-compat/android.hardware.camera.metadata@3.2.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.camera.provider@2.4.so:system/lib/vndk-compat/android.hardware.camera.provider@2.4.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.configstore-utils.so:system/lib/vndk-compat/android.hardware.configstore-utils.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.configstore@1.0.so:system/lib/vndk-compat/android.hardware.configstore@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.contexthub@1.0.so:system/lib/vndk-compat/android.hardware.contexthub@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.drm@1.0.so:system/lib/vndk-compat/android.hardware.drm@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.gatekeeper@1.0.so:system/lib/vndk-compat/android.hardware.gatekeeper@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.gnss@1.0.so:system/lib/vndk-compat/android.hardware.gnss@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.graphics.allocator@2.0.so:system/lib/vndk-compat/android.hardware.graphics.allocator@2.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.graphics.bufferqueue@1.0.so:system/lib/vndk-compat/android.hardware.graphics.bufferqueue@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.graphics.composer@2.1.so:system/lib/vndk-compat/android.hardware.graphics.composer@2.1.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.ir@1.0.so:system/lib/vndk-compat/android.hardware.ir@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.keymaster@3.0.so:system/lib/vndk-compat/android.hardware.keymaster@3.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.light@2.0.so:system/lib/vndk-compat/android.hardware.light@2.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.media.omx@1.0.so:system/lib/vndk-compat/android.hardware.media.omx@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.media@1.0.so:system/lib/vndk-compat/android.hardware.media@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.memtrack@1.0.so:system/lib/vndk-compat/android.hardware.memtrack@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.nfc@1.0.so:system/lib/vndk-compat/android.hardware.nfc@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.power@1.0.so:system/lib/vndk-compat/android.hardware.power@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.radio.deprecated@1.0.so:system/lib/vndk-compat/android.hardware.radio.deprecated@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.radio@1.0.so:system/lib/vndk-compat/android.hardware.radio@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.sensors@1.0.so:system/lib/vndk-compat/android.hardware.sensors@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.soundtrigger@2.0.so:system/lib/vndk-compat/android.hardware.soundtrigger@2.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.thermal@1.0.so:system/lib/vndk-compat/android.hardware.thermal@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.tv.cec@1.0.so:system/lib/vndk-compat/android.hardware.tv.cec@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.tv.input@1.0.so:system/lib/vndk-compat/android.hardware.tv.input@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.usb@1.0.so:system/lib/vndk-compat/android.hardware.usb@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.vibrator@1.0.so:system/lib/vndk-compat/android.hardware.vibrator@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.vr@1.0.so:system/lib/vndk-compat/android.hardware.vr@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.wifi.supplicant@1.0.so:system/lib/vndk-compat/android.hardware.wifi.supplicant@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hardware.wifi@1.0.so:system/lib/vndk-compat/android.hardware.wifi@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hidl.allocator@1.0.so:system/lib/vndk-compat/android.hidl.allocator@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hidl.base@1.0.so:system/lib/vndk-compat/android.hidl.base@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hidl.token@1.0-utils.so:system/lib/vndk-compat/android.hidl.token@1.0-utils.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.hidl.token@1.0.so:system/lib/vndk-compat/android.hidl.token@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/android.system.wifi.keystore@1.0.so:system/lib/vndk-compat/android.system.wifi.keystore@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libaudioroute.so:system/lib/vndk-compat/libaudioroute.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libaudioutils.so:system/lib/vndk-compat/libaudioutils.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libavservices_minijail.so:system/lib/vndk-compat/libavservices_minijail.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libbinder.so:system/lib/vndk-compat/libbinder.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libcamera_metadata.so:system/lib/vndk-compat/libcamera_metadata.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libcap.so:system/lib/vndk-compat/libcap.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libcrypto.so:system/lib/vndk-compat/libcrypto.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libcrypto_utils.so:system/lib/vndk-compat/libcrypto_utils.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libdiskconfig.so:system/lib/vndk-compat/libdiskconfig.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libevent.so:system/lib/vndk-compat/libevent.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libexif.so:system/lib/vndk-compat/libexif.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libexpat.so:system/lib/vndk-compat/libexpat.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libfmq.so:system/lib/vndk-compat/libfmq.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libgatekeeper.so:system/lib/vndk-compat/libgatekeeper.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libhardware_legacy.so:system/lib/vndk-compat/libhardware_legacy.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libjpeg.so:system/lib/vndk-compat/libjpeg.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libkeymaster1.so:system/lib/vndk-compat/libkeymaster1.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libkeymaster_messages.so:system/lib/vndk-compat/libkeymaster_messages.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libldacBT_abr.so:system/lib/vndk-compat/libldacBT_abr.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libldacBT_enc.so:system/lib/vndk-compat/libldacBT_enc.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/liblz4.so:system/lib/vndk-compat/liblz4.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libmedia_helper.so:system/lib/vndk-compat/libmedia_helper.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libmediacodecservice.so:system/lib/vndk-compat/libmediacodecservice.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libmemtrack.so:system/lib/vndk-compat/libmemtrack.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libminijail.so:system/lib/vndk-compat/libminijail.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libnetutils.so:system/lib/vndk-compat/libnetutils.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libnl.so:system/lib/vndk-compat/libnl.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libopus.so:system/lib/vndk-compat/libopus.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libpcre2.so:system/lib/vndk-compat/libpcre2.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libpiex.so:system/lib/vndk-compat/libpiex.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libpng.so:system/lib/vndk-compat/libpng.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libpower.so:system/lib/vndk-compat/libpower.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libprocinfo.so:system/lib/vndk-compat/libprocinfo.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libprotobuf-cpp-full.so:system/lib/vndk-compat/libprotobuf-cpp-full.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libprotobuf-cpp-lite.so:system/lib/vndk-compat/libprotobuf-cpp-lite.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libradio_metadata.so:system/lib/vndk-compat/libradio_metadata.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libselinux.so:system/lib/vndk-compat/libselinux.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libsoftkeymasterdevice.so:system/lib/vndk-compat/libsoftkeymasterdevice.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libspeexresampler.so:system/lib/vndk-compat/libspeexresampler.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libsqlite.so:system/lib/vndk-compat/libsqlite.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libssl.so:system/lib/vndk-compat/libssl.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_amrnb_common.so:system/lib/vndk-compat/libstagefright_amrnb_common.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_enc_common.so:system/lib/vndk-compat/libstagefright_enc_common.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_foundation.so:system/lib/vndk-compat/libstagefright_foundation.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_omx.so:system/lib/vndk-compat/libstagefright_omx.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_aacdec.so:system/lib/vndk-compat/libstagefright_soft_aacdec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_aacenc.so:system/lib/vndk-compat/libstagefright_soft_aacenc.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_amrdec.so:system/lib/vndk-compat/libstagefright_soft_amrdec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_amrnbenc.so:system/lib/vndk-compat/libstagefright_soft_amrnbenc.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_amrwbenc.so:system/lib/vndk-compat/libstagefright_soft_amrwbenc.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_avcdec.so:system/lib/vndk-compat/libstagefright_soft_avcdec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_avcenc.so:system/lib/vndk-compat/libstagefright_soft_avcenc.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_flacenc.so:system/lib/vndk-compat/libstagefright_soft_flacenc.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_g711dec.so:system/lib/vndk-compat/libstagefright_soft_g711dec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_gsmdec.so:system/lib/vndk-compat/libstagefright_soft_gsmdec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_hevcdec.so:system/lib/vndk-compat/libstagefright_soft_hevcdec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_mp3dec.so:system/lib/vndk-compat/libstagefright_soft_mp3dec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_mpeg2dec.so:system/lib/vndk-compat/libstagefright_soft_mpeg2dec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_mpeg4dec.so:system/lib/vndk-compat/libstagefright_soft_mpeg4dec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_mpeg4enc.so:system/lib/vndk-compat/libstagefright_soft_mpeg4enc.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_opusdec.so:system/lib/vndk-compat/libstagefright_soft_opusdec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_rawdec.so:system/lib/vndk-compat/libstagefright_soft_rawdec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_vorbisdec.so:system/lib/vndk-compat/libstagefright_soft_vorbisdec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_vpxdec.so:system/lib/vndk-compat/libstagefright_soft_vpxdec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_soft_vpxenc.so:system/lib/vndk-compat/libstagefright_soft_vpxenc.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libstagefright_xmlparser@1.0.so:system/lib/vndk-compat/libstagefright_xmlparser@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libsuspend.so:system/lib/vndk-compat/libsuspend.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libsysutils.so:system/lib/vndk-compat/libsysutils.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libtinyalsa.so:system/lib/vndk-compat/libtinyalsa.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libtinyxml2.so:system/lib/vndk-compat/libtinyxml2.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libui.so:system/lib/vndk-compat/libui.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libusbhost.so:system/lib/vndk-compat/libusbhost.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libutils.so:system/lib/vndk-compat/libutils.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libvixl-arm.so:system/lib/vndk-compat/libvixl-arm.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libvixl-arm64.so:system/lib/vndk-compat/libvixl-arm64.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libvorbisidec.so:system/lib/vndk-compat/libvorbisidec.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libwifi-service.so:system/lib/vndk-compat/libwifi-service.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libxml2.so:system/lib/vndk-compat/libxml2.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libyuv.so:system/lib/vndk-compat/libyuv.so \
    vendor/honor/stf/proprietary/lib/vndk-compat/libziparchive.so:system/lib/vndk-compat/libziparchive.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/android.hardware.graphics.allocator@2.0.so:system/lib/vndk-sp-compat/android.hardware.graphics.allocator@2.0.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/android.hardware.graphics.common@1.0.so:system/lib/vndk-sp-compat/android.hardware.graphics.common@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/android.hardware.graphics.mapper@2.0.so:system/lib/vndk-sp-compat/android.hardware.graphics.mapper@2.0.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/android.hardware.renderscript@1.0.so:system/lib/vndk-sp-compat/android.hardware.renderscript@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/android.hidl.base@1.0.so:system/lib/vndk-sp-compat/android.hidl.base@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/android.hidl.memory@1.0.so:system/lib/vndk-sp-compat/android.hidl.memory@1.0.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libRSCpuRef.so:system/lib/vndk-sp-compat/libRSCpuRef.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libRSDriver.so:system/lib/vndk-sp-compat/libRSDriver.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libRS_internal.so:system/lib/vndk-sp-compat/libRS_internal.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libbacktrace.so:system/lib/vndk-sp-compat/libbacktrace.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libbase.so:system/lib/vndk-sp-compat/libbase.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libbcinfo.so:system/lib/vndk-sp-compat/libbcinfo.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libblas.so:system/lib/vndk-sp-compat/libblas.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libc++.so:system/lib/vndk-sp-compat/libc++.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libcompiler_rt.so:system/lib/vndk-sp-compat/libcompiler_rt.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libcutils.so:system/lib/vndk-sp-compat/libcutils.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libft2.so:system/lib/vndk-sp-compat/libft2.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libhardware.so:system/lib/vndk-sp-compat/libhardware.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libhidlbase.so:system/lib/vndk-sp-compat/libhidlbase.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libhidlmemory.so:system/lib/vndk-sp-compat/libhidlmemory.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libhidltransport.so:system/lib/vndk-sp-compat/libhidltransport.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libhwbinder.so:system/lib/vndk-sp-compat/libhwbinder.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libion.so:system/lib/vndk-sp-compat/libion.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/liblzma.so:system/lib/vndk-sp-compat/liblzma.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libpng.so:system/lib/vndk-sp-compat/libpng.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libunwind.so:system/lib/vndk-sp-compat/libunwind.so \
    vendor/honor/stf/proprietary/lib/vndk-sp-compat/libutils.so:system/lib/vndk-sp-compat/libutils.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.frameworks.displayservice@1.0.so:system/lib64/vndk-compat/android.frameworks.displayservice@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.frameworks.schedulerservice@1.0.so:system/lib64/vndk-compat/android.frameworks.schedulerservice@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.frameworks.sensorservice@1.0.so:system/lib64/vndk-compat/android.frameworks.sensorservice@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.frameworks.vr.composer@1.0.so:system/lib64/vndk-compat/android.frameworks.vr.composer@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.audio.common@2.0-util.so:system/lib64/vndk-compat/android.hardware.audio.common@2.0-util.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.audio.common@2.0.so:system/lib64/vndk-compat/android.hardware.audio.common@2.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.audio.effect@2.0.so:system/lib64/vndk-compat/android.hardware.audio.effect@2.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.audio@2.0.so:system/lib64/vndk-compat/android.hardware.audio@2.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.biometrics.fingerprint@2.1.so:system/lib64/vndk-compat/android.hardware.biometrics.fingerprint@2.1.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.bluetooth@1.0.so:system/lib64/vndk-compat/android.hardware.bluetooth@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.boot@1.0.so:system/lib64/vndk-compat/android.hardware.boot@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.broadcastradio@1.0.so:system/lib64/vndk-compat/android.hardware.broadcastradio@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.broadcastradio@1.1.so:system/lib64/vndk-compat/android.hardware.broadcastradio@1.1.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.camera.common@1.0.so:system/lib64/vndk-compat/android.hardware.camera.common@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.camera.device@1.0.so:system/lib64/vndk-compat/android.hardware.camera.device@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.camera.device@3.2.so:system/lib64/vndk-compat/android.hardware.camera.device@3.2.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.camera.metadata@3.2.so:system/lib64/vndk-compat/android.hardware.camera.metadata@3.2.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.camera.provider@2.4.so:system/lib64/vndk-compat/android.hardware.camera.provider@2.4.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.configstore-utils.so:system/lib64/vndk-compat/android.hardware.configstore-utils.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.configstore@1.0.so:system/lib64/vndk-compat/android.hardware.configstore@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.contexthub@1.0.so:system/lib64/vndk-compat/android.hardware.contexthub@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.drm@1.0.so:system/lib64/vndk-compat/android.hardware.drm@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.gatekeeper@1.0.so:system/lib64/vndk-compat/android.hardware.gatekeeper@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.gnss@1.0.so:system/lib64/vndk-compat/android.hardware.gnss@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.graphics.allocator@2.0.so:system/lib64/vndk-compat/android.hardware.graphics.allocator@2.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.graphics.bufferqueue@1.0.so:system/lib64/vndk-compat/android.hardware.graphics.bufferqueue@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.graphics.composer@2.1.so:system/lib64/vndk-compat/android.hardware.graphics.composer@2.1.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.health@1.0.so:system/lib64/vndk-compat/android.hardware.health@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.ir@1.0.so:system/lib64/vndk-compat/android.hardware.ir@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.keymaster@3.0.so:system/lib64/vndk-compat/android.hardware.keymaster@3.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.light@2.0.so:system/lib64/vndk-compat/android.hardware.light@2.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.media.omx@1.0.so:system/lib64/vndk-compat/android.hardware.media.omx@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.media@1.0.so:system/lib64/vndk-compat/android.hardware.media@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.memtrack@1.0.so:system/lib64/vndk-compat/android.hardware.memtrack@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.nfc@1.0.so:system/lib64/vndk-compat/android.hardware.nfc@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.power@1.0.so:system/lib64/vndk-compat/android.hardware.power@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.radio.deprecated@1.0.so:system/lib64/vndk-compat/android.hardware.radio.deprecated@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.radio@1.0.so:system/lib64/vndk-compat/android.hardware.radio@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.sensors@1.0.so:system/lib64/vndk-compat/android.hardware.sensors@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.soundtrigger@2.0.so:system/lib64/vndk-compat/android.hardware.soundtrigger@2.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.thermal@1.0.so:system/lib64/vndk-compat/android.hardware.thermal@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.tv.cec@1.0.so:system/lib64/vndk-compat/android.hardware.tv.cec@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.tv.input@1.0.so:system/lib64/vndk-compat/android.hardware.tv.input@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.usb@1.0.so:system/lib64/vndk-compat/android.hardware.usb@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.vibrator@1.0.so:system/lib64/vndk-compat/android.hardware.vibrator@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.vr@1.0.so:system/lib64/vndk-compat/android.hardware.vr@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.wifi.supplicant@1.0.so:system/lib64/vndk-compat/android.hardware.wifi.supplicant@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hardware.wifi@1.0.so:system/lib64/vndk-compat/android.hardware.wifi@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hidl.allocator@1.0.so:system/lib64/vndk-compat/android.hidl.allocator@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hidl.base@1.0.so:system/lib64/vndk-compat/android.hidl.base@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hidl.token@1.0-utils.so:system/lib64/vndk-compat/android.hidl.token@1.0-utils.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.hidl.token@1.0.so:system/lib64/vndk-compat/android.hidl.token@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/android.system.wifi.keystore@1.0.so:system/lib64/vndk-compat/android.system.wifi.keystore@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libaudioroute.so:system/lib64/vndk-compat/libaudioroute.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libaudioutils.so:system/lib64/vndk-compat/libaudioutils.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libavservices_minijail.so:system/lib64/vndk-compat/libavservices_minijail.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libbinder.so:system/lib64/vndk-compat/libbinder.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libcamera_metadata.so:system/lib64/vndk-compat/libcamera_metadata.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libcap.so:system/lib64/vndk-compat/libcap.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libcrypto.so:system/lib64/vndk-compat/libcrypto.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libcrypto_utils.so:system/lib64/vndk-compat/libcrypto_utils.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libcurl.so:system/lib64/vndk-compat/libcurl.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libdiskconfig.so:system/lib64/vndk-compat/libdiskconfig.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libdumpstateutil.so:system/lib64/vndk-compat/libdumpstateutil.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libevent.so:system/lib64/vndk-compat/libevent.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libexif.so:system/lib64/vndk-compat/libexif.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libexpat.so:system/lib64/vndk-compat/libexpat.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libfmq.so:system/lib64/vndk-compat/libfmq.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libgatekeeper.so:system/lib64/vndk-compat/libgatekeeper.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libhardware_legacy.so:system/lib64/vndk-compat/libhardware_legacy.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libjpeg.so:system/lib64/vndk-compat/libjpeg.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libkeymaster1.so:system/lib64/vndk-compat/libkeymaster1.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libkeymaster_messages.so:system/lib64/vndk-compat/libkeymaster_messages.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libldacBT_abr.so:system/lib64/vndk-compat/libldacBT_abr.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libldacBT_enc.so:system/lib64/vndk-compat/libldacBT_enc.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/liblz4.so:system/lib64/vndk-compat/liblz4.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libmedia_helper.so:system/lib64/vndk-compat/libmedia_helper.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libmemtrack.so:system/lib64/vndk-compat/libmemtrack.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libminijail.so:system/lib64/vndk-compat/libminijail.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libnetutils.so:system/lib64/vndk-compat/libnetutils.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libnl.so:system/lib64/vndk-compat/libnl.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libopus.so:system/lib64/vndk-compat/libopus.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libpagemap.so:system/lib64/vndk-compat/libpagemap.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libpcre2.so:system/lib64/vndk-compat/libpcre2.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libpiex.so:system/lib64/vndk-compat/libpiex.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libpng.so:system/lib64/vndk-compat/libpng.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libpower.so:system/lib64/vndk-compat/libpower.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libprocinfo.so:system/lib64/vndk-compat/libprocinfo.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libprotobuf-cpp-full.so:system/lib64/vndk-compat/libprotobuf-cpp-full.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libprotobuf-cpp-lite.so:system/lib64/vndk-compat/libprotobuf-cpp-lite.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libradio_metadata.so:system/lib64/vndk-compat/libradio_metadata.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libselinux.so:system/lib64/vndk-compat/libselinux.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libsoftkeymasterdevice.so:system/lib64/vndk-compat/libsoftkeymasterdevice.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libspeexresampler.so:system/lib64/vndk-compat/libspeexresampler.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libsqlite.so:system/lib64/vndk-compat/libsqlite.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libssl.so:system/lib64/vndk-compat/libssl.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_amrnb_common.so:system/lib64/vndk-compat/libstagefright_amrnb_common.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_enc_common.so:system/lib64/vndk-compat/libstagefright_enc_common.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_foundation.so:system/lib64/vndk-compat/libstagefright_foundation.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_omx.so:system/lib64/vndk-compat/libstagefright_omx.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_aacdec.so:system/lib64/vndk-compat/libstagefright_soft_aacdec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_aacenc.so:system/lib64/vndk-compat/libstagefright_soft_aacenc.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_amrdec.so:system/lib64/vndk-compat/libstagefright_soft_amrdec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_amrnbenc.so:system/lib64/vndk-compat/libstagefright_soft_amrnbenc.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_amrwbenc.so:system/lib64/vndk-compat/libstagefright_soft_amrwbenc.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_avcdec.so:system/lib64/vndk-compat/libstagefright_soft_avcdec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_avcenc.so:system/lib64/vndk-compat/libstagefright_soft_avcenc.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_flacenc.so:system/lib64/vndk-compat/libstagefright_soft_flacenc.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_g711dec.so:system/lib64/vndk-compat/libstagefright_soft_g711dec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_gsmdec.so:system/lib64/vndk-compat/libstagefright_soft_gsmdec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_hevcdec.so:system/lib64/vndk-compat/libstagefright_soft_hevcdec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_mp3dec.so:system/lib64/vndk-compat/libstagefright_soft_mp3dec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_mpeg2dec.so:system/lib64/vndk-compat/libstagefright_soft_mpeg2dec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_mpeg4dec.so:system/lib64/vndk-compat/libstagefright_soft_mpeg4dec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_mpeg4enc.so:system/lib64/vndk-compat/libstagefright_soft_mpeg4enc.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_opusdec.so:system/lib64/vndk-compat/libstagefright_soft_opusdec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_rawdec.so:system/lib64/vndk-compat/libstagefright_soft_rawdec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_vorbisdec.so:system/lib64/vndk-compat/libstagefright_soft_vorbisdec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_vpxdec.so:system/lib64/vndk-compat/libstagefright_soft_vpxdec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libstagefright_soft_vpxenc.so:system/lib64/vndk-compat/libstagefright_soft_vpxenc.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libsuspend.so:system/lib64/vndk-compat/libsuspend.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libsysutils.so:system/lib64/vndk-compat/libsysutils.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libtinyalsa.so:system/lib64/vndk-compat/libtinyalsa.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libtinyxml2.so:system/lib64/vndk-compat/libtinyxml2.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libui.so:system/lib64/vndk-compat/libui.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libusbhost.so:system/lib64/vndk-compat/libusbhost.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libutils.so:system/lib64/vndk-compat/libutils.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libvixl-arm.so:system/lib64/vndk-compat/libvixl-arm.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libvixl-arm64.so:system/lib64/vndk-compat/libvixl-arm64.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libvorbisidec.so:system/lib64/vndk-compat/libvorbisidec.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libwifi-service.so:system/lib64/vndk-compat/libwifi-service.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libwifi-system.so:system/lib64/vndk-compat/libwifi-system.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libxml2.so:system/lib64/vndk-compat/libxml2.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libyuv.so:system/lib64/vndk-compat/libyuv.so \
    vendor/honor/stf/proprietary/lib64/vndk-compat/libziparchive.so:system/lib64/vndk-compat/libziparchive.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/android.hardware.graphics.allocator@2.0.so:system/lib64/vndk-sp-compat/android.hardware.graphics.allocator@2.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/android.hardware.graphics.common@1.0.so:system/lib64/vndk-sp-compat/android.hardware.graphics.common@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/android.hardware.graphics.mapper@2.0.so:system/lib64/vndk-sp-compat/android.hardware.graphics.mapper@2.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/android.hardware.renderscript@1.0.so:system/lib64/vndk-sp-compat/android.hardware.renderscript@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/android.hidl.base@1.0.so:system/lib64/vndk-sp-compat/android.hidl.base@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/android.hidl.memory@1.0.so:system/lib64/vndk-sp-compat/android.hidl.memory@1.0.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libRSCpuRef.so:system/lib64/vndk-sp-compat/libRSCpuRef.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libRSDriver.so:system/lib64/vndk-sp-compat/libRSDriver.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libRS_internal.so:system/lib64/vndk-sp-compat/libRS_internal.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libbacktrace.so:system/lib64/vndk-sp-compat/libbacktrace.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libbase.so:system/lib64/vndk-sp-compat/libbase.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libbcinfo.so:system/lib64/vndk-sp-compat/libbcinfo.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libblas.so:system/lib64/vndk-sp-compat/libblas.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libc++.so:system/lib64/vndk-sp-compat/libc++.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libcompiler_rt.so:system/lib64/vndk-sp-compat/libcompiler_rt.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libcutils.so:system/lib64/vndk-sp-compat/libcutils.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libft2.so:system/lib64/vndk-sp-compat/libft2.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libhardware.so:system/lib64/vndk-sp-compat/libhardware.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libhidlbase.so:system/lib64/vndk-sp-compat/libhidlbase.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libhidlmemory.so:system/lib64/vndk-sp-compat/libhidlmemory.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libhidltransport.so:system/lib64/vndk-sp-compat/libhidltransport.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libhwbinder.so:system/lib64/vndk-sp-compat/libhwbinder.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libion.so:system/lib64/vndk-sp-compat/libion.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/liblzma.so:system/lib64/vndk-sp-compat/liblzma.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libpng.so:system/lib64/vndk-sp-compat/libpng.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libunwind.so:system/lib64/vndk-sp-compat/libunwind.so \
    vendor/honor/stf/proprietary/lib64/vndk-sp-compat/libutils.so:system/lib64/vndk-sp-compat/libutils.so
